language: java
jdk:
  - openjdk7
  - oraclejdk7  
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'spring-angular' ]; then cd .. && eval "mv $currentfolder spring-angular" && cd spring-angular; fi
  - npm install -g bower grunt-cli grunt
  - bower install && npm install && grunt
